### ISSUE TITLE
The Cascade Picker doesn't scroll and just returns back to the first value.

### ISSUE THREAD

**Issue by ahmadaba14** [yorickshan/rn-cascade-picker#2]
Whenever i drag the cascade picker to scroll it doesn't scroll and just returns back to its position. 
https://user-images.githubusercontent.com/46707661/170863379-de406ca8-f320-48f9-bc31-409be3ab3ac1.mp4
This is my code:
`<CascadePicker
    visible={pickerVisible}
                data={carData}
                cols={4}
                title="Select Car"
                cancelText="cancel"
                confirmText = "confirm"
                value={['1', '2', '3', '4']}
                onCancel={() => setPickerVisible(false)}
                onConfirm={(val) => {
                    console.log(val)
                    setPickerVisible(false)
                }}
            />`

**Comment by yorickshan** [comment]
what's your platform, can you show me the detail of 'carData' ?
